services:
  manu_dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: manu_dev
    volumes:
      - type: bind
        source: .
        target: /app/
    ports:
      - "3000:3000"
      - "3001:3001"
      - "9229:9229"
      - "9230:9230"
  # nginx:
  #   build:
  #     context: ./proxy
  #     dockerfile: Dockerfile.nginx
  #   ports:
  #     - "3002:80"
