services:
  manu_dev:
    container_name: manu_dev
    image: manu_dev:latest
    volumes:
      - type: bind
        source: .
        target: /app/
    ports:
      - "3000:3000"
      - "3001:3001"