services:
  manu_dev:
    container_name: manu_dev
    environment:
      - NODE_OPTIONS='--inspect'
    image: manu_dev:latest
    volumes:
      - type: bind
        source: .
        target: /app/
    ports:
      - "3000:3000"
      - "3001:3001"
      - "9229:9229"
  nginx:
    image: nginx